### ISSUE TITLE
TOTOLINK-X5000R-PASSWALL-SSR-IMMO-V21_2022.04.01-1734

### ISSUE THREAD

**Issue by akram1447** [MatJeheyy/Openwrt-Firmware-By-Shisui-Collection#1]
saya flash openwrt-by-shisui-21.02-r19269-be0d1b2827-ramips-mt7621-totolink_x5000r-initramfs-kernel

ke totolink saya.. nak login openwrt ada password. boleh bagi password? sebab totolink sy tak boleh nk flash kalau tak ada password

**Comment by MatJeheyy** [comment]
password : password
